[package]
name = "prolog_rs"
version = "0.1.0"
authors = ["Ivan Gusiev <ivan.gusiev@gmail.com>"]

[dependencies]
crossterm = "0.26.0"
peg = "0.8.1"
rustyline = "10.1.1"
string-interner = "0.14.0"
tui = "0.19.0"

[dev-dependencies]
insta = "1.26.0"
parameterized = "1.0.1"
