[package]
name = "prolog_rs"
version = "0.1.0"
authors = ["Ivan Gusiev <ivan.gusiev@gmail.com>"]

[dependencies]
peg = "0.8.1"
topological-sort = "0.2.2"

[dev-dependencies]
insta = "1.26.0"
parameterized = "1.0.1"
